// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBmsIpZDyEJsJAt49fYvlT9IMBbSLqFzso',
    appId: '1:784407085372:web:e6401725e0c48d91025e39',
    messagingSenderId: '784407085372',
    projectId: 'cicerone-99155',
    authDomain: 'cicerone-99155.firebaseapp.com',
    storageBucket: 'cicerone-99155.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDu62PoswtGQOtKKzwzlBC0ejEI8Edocko',
    appId: '1:784407085372:android:9d6611a3a331a24d025e39',
    messagingSenderId: '784407085372',
    projectId: 'cicerone-99155',
    storageBucket: 'cicerone-99155.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB57lLZbfAZp0eI0_6DucRqz_wSpjjABEs',
    appId: '1:784407085372:ios:b365a5f18e81fd1f025e39',
    messagingSenderId: '784407085372',
    projectId: 'cicerone-99155',
    storageBucket: 'cicerone-99155.appspot.com',
    iosClientId: '784407085372-uufmtgrhh2dfa9ivapifhbcshreuj6qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB57lLZbfAZp0eI0_6DucRqz_wSpjjABEs',
    appId: '1:784407085372:ios:b365a5f18e81fd1f025e39',
    messagingSenderId: '784407085372',
    projectId: 'cicerone-99155',
    storageBucket: 'cicerone-99155.appspot.com',
    iosClientId: '784407085372-uufmtgrhh2dfa9ivapifhbcshreuj6qh.apps.googleusercontent.com',
    iosBundleId: 'com.example.projects',
  );
}
